name: Production Deployment on AWS EC2

env:
  AWS_EC2_USER: ${{ secrets.AWS_EC2_USER }}
  AWS_EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  APP_NAME: tsa-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check linting and formatting
        run: |
          yarn eslint "**/*.{ts,js}" .
          yarn prettier --check .

      - name: Generate Prisma Client
        run: yarn prisma generate

      - name: Build NestJS Project
        run: yarn build

      - name: Create SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$AWS_EC2_HOST" > ~/.ssh/known_hosts

      - name: Deploy to AWS EC2
        run: |
          rsync \
            -avz --delete \
            --exclude 'node_modules' --exclude '.env' \
            ./dist ./prisma ./package.json ./yarn.lock $AWS_EC2_USER@$AWS_EC2_HOST:/home/$AWS_EC2_USER/$APP_NAME

      - name: Restart the server
        run: |
          ssh $AWS_EC2_USER@$AWS_EC2_HOST <<EOF
            export PATH="$PATH:/home/$AWS_EC2_USER/.nvm/versions/node/v22.14.0/bin"
            set -e
            cd /home/$AWS_EC2_USER/$APP_NAME
            yarn install --frozen-lockfile
            yarn prisma generate
            pm2 restart $APP_NAME || pm2 start "yarn start:prod" --name "$APP_NAME"
          EOF
